# Generated by Django 3.2.5 on 2021-10-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
