# Generated by Django 3.2.7 on 2021-10-09 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('group', models.IntegerField()),
                ('body_text', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновление публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('specifications', models.FileField(upload_to='Files')),
                ('link', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашка',
                'verbose_name_plural': 'Домашка',
                'ordering': ['-created_at'],
            },
        ),
    ]
